server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    #전송 쿼리 확인
    show-sql: true # 실행되는 SQL 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # SQL을 줄바꿈해서 보기 좋게 출력

    #테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
  jwt:
    issuer: sune0410@g.yju.ac.kr
    secret_kye: study-springboot
